spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://192.168.2.55:3306/test}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.mvc.converters.preferred-json-mapper = gson
spring.jpa.defer-datasource-initialization=true